Models/Player.cs
using System.ComponentModel.DataAnnotations;

namespace RpgGame.Models
{
    public class Player
    {
        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int ClassId { get; set; }
        public int Strength { get; set; }
        public int MagicPower { get; set; }
        public int Armor { get; set; }
        public int Dexterity { get; set; }
        public int Swiftness { get; set; }
        public int Health { get; set; }
        public byte[] ?ItemArray { get; set; }
        public Guid AccountId { get; set; }
        






    }
}

Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NuGet.Versioning;
using RpgGame.Data;
using RpgGame.Functions;
using RpgGame.Models;

namespace RpgGame.Controllers
{
    public class PlayersController : Controller
    {
        private IHttpContextAccessor _httpContextAccessor;
        private readonly UserManager<Account> _userManager;
        private readonly SignInManager<Account> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        private readonly RpgContext _context;

        public PlayersController(IHttpContextAccessor httpContextAccessor,RpgContext context, UserManager<Account> userManager,SignInManager<Account> signInManager,RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _httpContextAccessor = httpContextAccessor;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }


    
        [HttpGet]
        public async Task<IActionResult> Index()
        {
              string name = _httpContextAccessor.HttpContext?.User.Identity.Name;

            if(name == null)
            {
                var user = _userManager.FindByNameAsync(name);
                
                if(user == null)
                {
                    return RedirectToAction(nameof(AccessDenied));
                }
            }
            else
            {
               
                var user = await _userManager.FindByNameAsync(name);
                ViewBag.currUser = user;
               
                return View();
            }
            return RedirectToAction(nameof(AccessDenied));

        }

        public async Task<IActionResult> Login()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Login([Bind("UserName,Password")] Account account)
        {
            List<Account> accList = _context.playerAccounts.ToList();
            var user = _userManager.FindByNameAsync(account.UserName);

            string username = account.Name;
         
            Account acc = accList.Find(c => c.UserName == username);
            var PasswordResult = _userManager.PasswordHasher.VerifyHashedPassword(user.Result, user.Result.PasswordHash, account.Password);
            if (PasswordResult == PasswordVerificationResult.Success)
            {
                var result = _signInManager.PasswordSignInAsync(user.Result.UserName,account.Password,false,false);
                if (result.Result.Succeeded)
                {
               
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction(nameof(Login));
                }
               
            }
            else
            {
                return RedirectToAction(nameof(AccessDenied));
            }
            


        }
        public async Task<IActionResult> Register()
        {

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Register([Bind("Name,Email,Password")] Account account)
        {
            Account acc = new Account {Name=account.Name, UserName = account.Name,Email=account.Email,AccountId = Guid.NewGuid()};

            var result = await _userManager.CreateAsync(acc,account.Password);
            if (result.Succeeded)
            {
                
                var defaultrole = _roleManager.FindByNameAsync("player").Result;
                IdentityResult roleResult = await _userManager.AddToRoleAsync(acc, defaultrole.Name);
                return RedirectToAction(nameof(Login));
                _context.Add(account);
                await _context.SaveChangesAsync();
            }
          

            
                return RedirectToAction(nameof(Register));
 
        }
        public IActionResult AccessDenied()
        {
            return View();
        }
        public async Task<IActionResult> Logout()
        {
            string Accname = _httpContextAccessor.HttpContext?.User.Identity.Name;
            await _signInManager.SignOutAsync();

            return RedirectToAction(nameof(Login));
        }
        public async Task<IActionResult> AccessPlayer()
        {
            List<Player> AllPlayersList = _context.players.ToList();
            string accName = _httpContextAccessor.HttpContext?.User.Identity.Name;

            var user = _userManager.FindByNameAsync(accName).Result;
            Guid accId = user.AccountId;

            List<Player> currPlayers = AllPlayersList.FindAll(c => c.AccountId == accId);
            ViewBag.currPlayers = currPlayers;
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> CreatePlayer()
        {
            List<Classes> classes = _context.classes.ToList();
            ViewBag.classes = classes;


            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreatePlayer([Bind("Name,ClassId")] Player player)
        {
            List<Classes> classes = _context.classes.ToList();
            string accName = _httpContextAccessor.HttpContext?.User.Identity.Name;
            var user = _userManager.FindByNameAsync(accName).Result;
            ViewBag.classes = classes;
            Player newPlayer = PlayerCommands.CreatePlayer(player.Name, player.ClassId,user.AccountId);
            _context.players.Add(newPlayer);
            _context.SaveChanges();

            return View();
        }
        public async Task<IActionResult> MainPlayerView([Bind("Id")] Player PlayerIdObject)
        {
            Guid PlayerId = PlayerIdObject.Id;
            Player player = _context.players.Find(PlayerId);
            Opponents oppo = new Opponents();
            oppo.Health = 100;
            PlayerCommands.Fight(player,oppo);
           

            return View();
        }


    }
       
    }

Views/Players/AccessDenied.cshtml
<h1><b>Access Denied</b></h1>

Something went wrong when logging in.
<br /><br />
<b>Try to log in again =></b> <a asp-action="Login">Log in</a>

Views/Players/AccessPlayer.cshtml
@model Player
@{
    List<Player> playerList = ViewBag.currPlayers;
    @foreach(Player player in playerList)
    {
    @using (Html.BeginForm("MainPlayerView", "Players", FormMethod.Post))
{
    <input style="visibility:hidden;position:absolute;" asp-for="Id" type="text" value="@player.Id">
    <button class="playerContainer" type="submit" id="cmdAction" runat="server">
                @player.Name<br>@player.Health<br>@player.ClassId<br>
    </button>
}



    }


}

Views/Players/CreatePlayer.cshtml
 @model RpgGame.Models.Player  
 <h1>Create your new character</h1>
        <form asp-action="CreatePlayer">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ClassId" class="control-label"></label>
                            <select asp-for=ClassId>
                            @foreach(Classes PlayerClass in ViewBag.classes){
                                <option value=@PlayerClass.Id>@PlayerClass.Name | @PlayerClass.Power</option>
                            }
                            </select>
                            <span asp-validation-for="ClassId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Zarejestruj" class="btn btn-primary" />
                        </div>
                    </form>

Views/Players/Index.cshtml
@model RpgGame.Models.Player
@{
    var user = ViewBag.currUser;


  
    <div>Logged in as: @user.Name</div>
    
     <a asp-action="CreatePlayer">Create a new character!</a><br />
     <a asp-action="AccessPlayer">Already have an character? => Choose him!</a>
}

Views/Players/Login.cshtml
@model RpgGame.Models.Account
<html>
<head>


    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="flex-container">
        <div class="flex-item">
            <h1 style="text-align:center;"><b>Login</b></h1>
            <br />
            <hr />
            <div style="align-items:center;"  class="row">
                <div class="col-md-4">
                    <form asp-action="Login">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="UserName" class="control-label"></label>
                            <input asp-for="UserName" class="form-control" />
                            <span asp-validation-for="UserName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Password" class="control-label"></label>
                            <input type="password" asp-for="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Zarejestruj" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
             Don't have an account? => <a asp-action="Register">Register now! </a>

        

            @section Scripts {
                @{
                    await Html.RenderPartialAsync("_ValidationScriptsPartial");
                }
            }


            </div>
        </div>





    </body>
    </html>

Views/Players/Logout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Players/Register.cshtml
@model RpgGame.Models.Account
<html>
<head>


    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="flex-container">
        <div class="flex-item">
            <h1><b>Register</b></h1>
            <br />
            <hr />
            <div style="align-items:center;"  class="row">
                <div class="col-md-4">
                    <form asp-action="Register">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="control-label"></label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Password" class="control-label"></label>
                            <input type="password" asp-for="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Zarejestruj" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
            Already have an account? => <a asp-action="Login">Login</a>
           

            @section Scripts {
                @{
                    await Html.RenderPartialAsync("_ValidationScriptsPartial");
                }
            }


            </div>
        </div>





    </body>
    </html>